### ISSUE TITLE
[FEATURE] zoom/move camera in 3D view?

### ISSUE THREAD

**Issue by erwincoumans** [ScaledFoundations/GRID-Forum#3]
**Is your feature request related to a problem? Please describe.**

After starting a session (see attached screenshot), I tried to zoom in or move the camera around the 3d view, on a Macbook. It is a basic feature in most simulators (MuJoCo, Isaac Sim etc) to inspect the robot in 3D. Did I miss the feature? I asked the AI and it told that the feature is not available.

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/4caec243-9410-4205-b688-1a862a238083">

Having mouse control in the simulated 3D view would be great. Or if it is already available, make it easy to discover how to.

**Comment by saihv** [comment]
@erwincoumans GRID currently allows keyboard control for zooming/moving camera within the simulation. You'll have to click on the simulation panel and use the keyboard shortcut M to enter manual camera mode (and then arrow keys/WSAD to move around). More keyboard shortcuts can be found here: https://docs.scaledfoundations.ai/airgen/apis/keyboard_shortcuts.html. We will work on making these options more visible in the documentation, and look into adding mouse control as well.

**Comment by erwincoumans** [comment]
Thanks, those keyboard shortcuts work (usually W,A,S,D are used for translation, not rotation though, mouse would be nice).
Let's close the issue, no need to flood this issue tracker :-)
